version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
      nodejs: 12
  build:
    commands:
      - ./build.sh
  post_build:
    commands:
      - echo Build completed `date`
artifacts:
  files:
    - backend/target/speech-helper-0.0.1-SNAPSHOT.jar